### ISSUE TITLE
Avoid redeploying all demos every time a change is made in the src directory

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/demos#80]

**Comment by CaroFG** [comment]
@nicolasvienot I've been told you are the Vercel expert 😄 do you know if this is possible? I have not found a way of doing it in the Vercel settings

**Comment by shivaylamba** [comment]
https://vercel.com/support/articles/how-do-i-use-the-ignored-build-step-field-on-vercel 
This might be beneficial

**Comment by CaroFG** [comment]
Exactly!

**Comment by nicolasvienot** [comment]
You can find more information [about monorepos and Vercel here](https://vercel.com/blog/monorepos).

As @shivaylamba pointed out, you should use the `Ignored Build Step` in order to manage this. What you can do is add an `Ignored Build Step` for each project that will only allow the deployment if there is a diff between the previously deployed version and the new one in git.

For example, in a simple version and for the project `MoMa`, you could add an `Ignored Build Step` like this:
```bash
git diff HEAD^ HEAD --quiet ./src/MoMa
```

You can add it directly in Vercel in `Settings/Git` for each project, or create a script in each folder and then just execute the script in the `Ignored Build Step.

Let me know if you need any help!

**Comment by CaroFG** [comment]
Thank you @nicolasvienot!

**Comment by CaroFG** [comment]
According to [this article](https://vercel.com/support/articles/how-do-i-use-the-ignored-build-step-field-on-vercel)
![Capture d’écran 2022-05-31 à 11 06 05](https://user-images.githubusercontent.com/48251481/171136832-3e4f1639-c8dd-479c-9cdd-c339a539af8c.png)

If the root directory is set to 'src/MoMA', like so: 
![Capture d’écran 2022-05-31 à 11 17 52](https://user-images.githubusercontent.com/48251481/171139273-ff2f8e7f-9ba4-4af7-92aa-9f64819bf6d7.png)

the command should be the following:
`git diff HEAD^ HEAD --quiet .`

Is that right?

**Comment by nicolasvienot** [comment]
> According to [this article](https://vercel.com/support/articles/how-do-i-use-the-ignored-build-step-field-on-vercel) ![Capture d’écran 2022-05-31 à 11 06 05](https://user-images.githubusercontent.com/48251481/171136832-3e4f1639-c8dd-479c-9cdd-c339a539af8c.png)
> 
> If the root directory is set to 'src/MoMA', like so: ![Capture d’écran 2022-05-31 à 11 17 52](https://user-images.githubusercontent.com/48251481/171139273-ff2f8e7f-9ba4-4af7-92aa-9f64819bf6d7.png)
> 
> the command should be the following: `git diff HEAD^ HEAD --quiet .`
> 
> Is that right?

Yes, totally. My bad I didn't see the comment about the `Root directory`.
That's nice because you can use the same command for all demos projects and even write it in the `Maintainer guidelines` 😄
